name: Indent

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    container: dealii/dealii:master-focal

    steps:
    - uses: actions/checkout@v2
    - name: Check indentation
      run: |
         ./scripts/check_indentation.sh 
