name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  debug:

    runs-on: ubuntu-latest
    container: dealii/dealii:master-focal

    steps:
    - uses: actions/checkout@v2
    - name: Build debug
      run: |
         rm -rf build_linux_debug
         mkdir build_linux_debug 
         cd build_linux_debug 
         cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
         ninja
    - name: Test debug
      run: |
         cd build_linux_debug
         ctest -N; 
         ctest --output-on-failure

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test release
      run: |
          rm -rf build_linux_release
          mkdir build_linux_release
          cd build_linux_release
          cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
          ninja
    - name: Test release
      run: |
          cd build_linux_release
          ctest -N 
          ctest --output-on-failure
